# Generated by Django 4.2 on 2025-05-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_post_notification_comment_bookmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Comment'},
        ),
    ]
